apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: {{ .Values.fastapi.port }}
      targetPort: {{ .Values.fastapi.port }}
      nodePort: {{ .Values.fastapi.nodePort }}
