version: '3.3'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: lookup_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres/lookup_service
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres
volumes:
  postgres_data:
