apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: bXl1c2Vy  # Base64 encoded username 
  postgres-password: bXlwYXNzd29yZA==  # Base64 encoded password 
  postgres-db: bG9va3VwX3NlcnZpY2U=  # Base64 encoded database name
