apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort  # Or LoadBalancer if you're using a cloud provider
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000  # For NodePort
