postgres:
  user: myuser
  password: mypassword
  db: lookup_service

fastapi:
  image: irfan611/fastapitsk:"latest"
  port: 3000
  nodePort: 30000
persistence:
  postgres:
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    storage: 5Gi
